### ISSUE TITLE
Areas unlocked from the start

### ISSUE THREAD

**Issue by DaEgi01** [ZenyaIse/Cities-Skylines-Extended-Game-Options#1]
A handy feature would be the option to set the number of area titles you start with directly.
Dropdown with:
1 (default)
9
25

**Comment by ZenyaIse** [comment]
1 and 25 are OK, but 9 tiles option is not simple because the starting tile may be not in the center of the map.

**Comment by DaEgi01** [comment]
ok, bad assumption from my side.
never made a real map myself ^^
a 1 or 25 option is not worth it if you ask me.
