### ISSUE TITLE
DistantAreasMod

### ISSUE THREAD

**Issue by DaEgi01** [ZenyaIse/Cities-Skylines-Extended-Game-Options#2]
It would be awesome if this mod:
http://steamcommunity.com/sharedfiles/filedetails/?id=412191763
could be incorporated.

I love to start the game with multiple smaller towns that grow together organically after a while.

**Comment by ZenyaIse** [comment]
Very good mod, but I'm not sure it needs to be incorporated.

**Comment by DaEgi01** [comment]
why do you think that it does not fit?

**Comment by ZenyaIse** [comment]
This mod is supposed to be as simple as possible - just adds several options to the game.
For something more complicated - use other mods.
