### ISSUE TITLE
Remove tile purchase feature?

### ISSUE THREAD

**Issue by originalfoo** [ZenyaIse/Cities-Skylines-Extended-Game-Options#4]
There are several decent tile purchase mods for user to choose from:

* Purchase It (an improved alternative to DistantAreasMod and the plethora of '25 ttiles' mods)
* 81 Tiles (latest version)

Would it be worth removing the purchase tiles feature from Extended Game Options mod to reduce  overlap with the other mods?

**Comment by ZenyaIse** [comment]
There is the solution.
Uncheck "Set number of purchasable areas" for compatibility with other modes.
